module.exports = {
  at: "2023-08-17T02:41:52.255Z",
  products: [
    {
      description: "amet esse labore incididunt",
      name: "officia",
      price: 1738.68,
      tmpProperty: undefined,
      activePromoId: 57,
    },
    {
      description: "consequat velit voluptate consequat",
      name: "aliqua",
      price: 1666.31,
      tmpProperty: undefined,
      activePromoId: 5,
    },
    {
      description: "deserunt cupidatat ad id",
      name: "sunt",
      price: 1217.24,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "excepteur laboris tempor ea",
      name: "sit",
      price: 1499.76,
      tmpProperty: undefined,
      activePromoId: 86,
    },
    {
      description: "qui minim sit in",
      name: "elit",
      price: 1104.65,
      tmpProperty: undefined,
      activePromoId: 48,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: "fugiat aute ut cillum",
      name: "aute",
      price: 983.77,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "consequat amet cillum cillum",
      name: "aliquip",
      price: 270.89,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "minim laboris eu incididunt",
      name: "sunt",
      price: 780.71,
      tmpProperty: undefined,
      activePromoId: 32,
    },
    {
      description: "dolor non excepteur sunt",
      name: "commodo",
      price: 586.01,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {},
    {
      description: "sint labore consequat deserunt",
      name: "esse",
      price: 1199.09,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cupidatat consequat excepteur id",
      name: "excepteur",
      price: 935.69,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "est magna labore duis",
      name: "nulla",
      price: 148.99,
      tmpProperty: undefined,
      activePromoId: 1,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: "Lorem eu irure id",
      name: "culpa",
      price: 1230.69,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nisi cupidatat Lorem minim",
      name: "ipsum",
      price: 1386.07,
      tmpProperty: undefined,
      activePromoId: 19,
    },
    {
      description: "enim consequat occaecat laboris",
      name: "enim",
      price: 1668.21,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eiusmod dolor nulla incididunt",
      name: "tempor",
      price: 1301.88,
      tmpProperty: undefined,
      activePromoId: 26,
    },
    {
      description: "velit dolore mollit ad",
      name: "duis",
      price: 1333.86,
      tmpProperty: undefined,
      activePromoId: 60,
    },
    {
      description: "aute sit incididunt dolore",
      name: "consectetur",
      price: 1710.95,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "labore aliquip ea deserunt",
      name: "Lorem",
      price: 562.27,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {
      description: "fugiat nostrud non commodo",
      name: "nisi",
      price: 478.82,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "officia cupidatat enim adipisicing",
      name: "in",
      price: 776.16,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "veniam laboris cupidatat nisi",
      name: "sint",
      price: 1882.96,
      tmpProperty: undefined,
      activePromoId: 43,
    },
    {
      description: "minim est dolore ipsum",
      name: "sunt",
      price: 1673.67,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "do est nostrud eiusmod",
      name: "nisi",
      price: 1791.55,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "voluptate sit sunt incididunt",
      name: "fugiat",
      price: 830.88,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliqua anim laborum ex",
      name: "et",
      price: 1170.47,
      tmpProperty: undefined,
      activePromoId: 18,
    },
    {
      description: "ut ut tempor cillum",
      name: "veniam",
      price: 699.56,
      tmpProperty: undefined,
      activePromoId: 83,
    },
    {
      description: "mollit commodo amet enim",
      name: "labore",
      price: 1129.21,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliquip incididunt consequat adipisicing",
      name: "enim",
      price: 746,
      tmpProperty: undefined,
      activePromoId: 32,
    },
    {
      description: "tempor officia quis deserunt",
      name: "nisi",
      price: 1457.96,
      tmpProperty: undefined,
      activePromoId: 100,
    },
    {
      description: "aliqua tempor occaecat qui",
      name: "deserunt",
      price: 1274.59,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "incididunt nulla ad labore",
      name: "non",
      price: 1064.96,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {
      description: "consequat ad aute ex",
      name: "non",
      price: 962,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "Lorem exercitation cupidatat qui",
      name: "proident",
      price: 539.61,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "pariatur qui elit cupidatat",
      name: "et",
      price: 1515.22,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "laboris nulla sint incididunt",
      name: "pariatur",
      price: 885.86,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cillum velit id eiusmod",
      name: "officia",
      price: 183.67,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "quis esse Lorem magna",
      name: "qui",
      price: 1685.06,
      tmpProperty: undefined,
      activePromoId: 87,
    },
    {
      description: "enim et ipsum officia",
      name: "tempor",
      price: 1893.96,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cupidatat non et adipisicing",
      name: "dolor",
      price: 1289.96,
      tmpProperty: undefined,
      activePromoId: 57,
    },
    {
      description: "Lorem commodo proident veniam",
      name: "anim",
      price: 1188.09,
      tmpProperty: undefined,
      activePromoId: 74,
    },
    {
      description: "nisi aute nisi nisi",
      name: "pariatur",
      price: 1661.84,
      tmpProperty: undefined,
      activePromoId: 0,
    },
    {
      description: "occaecat commodo minim ex",
      name: "dolor",
      price: 1252.15,
      tmpProperty: undefined,
      activePromoId: 8,
    },
    {
      description: "cillum culpa laborum consequat",
      name: "nostrud",
      price: 1789.23,
      tmpProperty: undefined,
      activePromoId: 13,
    },
    {
      description: "adipisicing quis consequat tempor",
      name: "velit",
      price: 1414.83,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "non Lorem ex voluptate",
      name: "Lorem",
      price: 1837.97,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "elit tempor dolor consequat",
      name: "duis",
      price: 1216.2,
      tmpProperty: undefined,
      activePromoId: 45,
    },
    {
      description: "voluptate labore Lorem irure",
      name: "qui",
      price: 1795.56,
      tmpProperty: undefined,
      activePromoId: 48,
    },
    {
      description: "id esse eu commodo",
      name: "eiusmod",
      price: 850.32,
      tmpProperty: undefined,
      activePromoId: 13,
    },
    {
      description: "fugiat officia deserunt laborum",
      name: "cillum",
      price: 1879.52,
      tmpProperty: undefined,
      activePromoId: 39,
    },
    {
      description: "nostrud ut ex duis",
      name: "dolor",
      price: 775.21,
      tmpProperty: undefined,
      activePromoId: 65,
    },
    {
      description: "aliqua consequat in sunt",
      name: "tempor",
      price: 122.75,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {
      description: "tempor aliqua amet minim",
      name: "occaecat",
      price: 1849.16,
      tmpProperty: undefined,
      activePromoId: 49,
    },
    {
      description: "magna excepteur id sit",
      name: "culpa",
      price: 1240.84,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "adipisicing adipisicing mollit tempor",
      name: "nulla",
      price: 301.23,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "labore consectetur mollit pariatur",
      name: "do",
      price: 1174.8,
      tmpProperty: undefined,
      activePromoId: 17,
    },
    {
      description: "exercitation esse ad ipsum",
      name: "consectetur",
      price: 915.58,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "velit voluptate sint mollit",
      name: "eu",
      price: 221.8,
      tmpProperty: undefined,
      activePromoId: 68,
    },
    {
      description: "ea ullamco minim sit",
      name: "minim",
      price: 1483.05,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "proident tempor irure deserunt",
      name: "exercitation",
      price: 118.29,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "et in est pariatur",
      name: "sint",
      price: 626.58,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "incididunt aute labore Lorem",
      name: "cillum",
      price: 1963.26,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cupidatat anim enim ipsum",
      name: "laborum",
      price: 1417.07,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "veniam culpa cupidatat nisi",
      name: "esse",
      price: 1216.49,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "officia amet aute voluptate",
      name: "Lorem",
      price: 1016.41,
      tmpProperty: undefined,
      activePromoId: 56,
    },
    {
      description: "eiusmod laborum quis esse",
      name: "cillum",
      price: 948.47,
      tmpProperty: undefined,
      activePromoId: 42,
    },
    {
      description: "non exercitation enim qui",
      name: "do",
      price: 348.34,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "consequat in sit velit",
      name: "nulla",
      price: 1508.88,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cupidatat ea consectetur nostrud",
      name: "voluptate",
      price: 116.04,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolore do cupidatat elit",
      name: "mollit",
      price: 1843.58,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "veniam aliquip tempor incididunt",
      name: "cupidatat",
      price: 1189.8,
      tmpProperty: undefined,
      activePromoId: 87,
    },
    {
      description: "commodo incididunt eu ut",
      name: "cupidatat",
      price: 357.1,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "deserunt sit voluptate cupidatat",
      name: "enim",
      price: 912.72,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "commodo incididunt elit dolor",
      name: "aute",
      price: 1188.96,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eiusmod laboris cupidatat ut",
      name: "incididunt",
      price: 568.58,
      tmpProperty: undefined,
      activePromoId: 12,
    },
    {
      description: "ut dolor ea consectetur",
      name: "Lorem",
      price: 1659.46,
      tmpProperty: undefined,
      activePromoId: 85,
    },
    {
      description: "et laborum anim ut",
      name: "consequat",
      price: 1941.6,
      tmpProperty: undefined,
      activePromoId: 38,
    },
    {
      description: "deserunt nulla nostrud ullamco",
      name: "sint",
      price: 821.07,
      tmpProperty: undefined,
      activePromoId: 37,
    },
    {
      description: "dolor mollit qui ullamco",
      name: "enim",
      price: 1249.79,
      tmpProperty: undefined,
      activePromoId: 23,
    },
    {
      description: "consectetur ipsum voluptate occaecat",
      name: "tempor",
      price: 1954.17,
      tmpProperty: undefined,
      activePromoId: 89,
    },
    {
      description: "sint qui nulla enim",
      name: "fugiat",
      price: 147.14,
      tmpProperty: undefined,
      activePromoId: 38,
    },
    {
      description: "voluptate id magna veniam",
      name: "culpa",
      price: 281.52,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "et dolore dolore ullamco",
      name: "magna",
      price: 199.32,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "anim do minim sint",
      name: "ipsum",
      price: 742.21,
      tmpProperty: undefined,
      activePromoId: 75,
    },
    {
      description: "consectetur adipisicing mollit fugiat",
      name: "excepteur",
      price: 497.79,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "enim cillum quis consequat",
      name: "voluptate",
      price: 1490.74,
      tmpProperty: undefined,
      activePromoId: 38,
    },
    {
      description: "proident ipsum voluptate sit",
      name: "consectetur",
      price: 1995.06,
      tmpProperty: undefined,
      activePromoId: 87,
    },
    {
      description: "do do reprehenderit aute",
      name: "laboris",
      price: 765.45,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {
      description: "cupidatat proident culpa incididunt",
      name: "magna",
      price: 1925.89,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ex veniam minim deserunt",
      name: "laborum",
      price: 466.73,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "qui officia pariatur esse",
      name: "fugiat",
      price: 385.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "est non dolor veniam",
      name: "proident",
      price: 1151.81,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "veniam excepteur cillum ex",
      name: "do",
      price: 104.17,
      tmpProperty: undefined,
      activePromoId: 44,
    },
    {
      description: "esse aute officia duis",
      name: "tempor",
      price: 1995.81,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sint duis sint duis",
      name: "adipisicing",
      price: 982.25,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "Lorem aute est occaecat",
      name: "commodo",
      price: 1100.25,
      tmpProperty: undefined,
      activePromoId: 68,
    },
    {
      description: "esse amet laboris laborum",
      name: "nostrud",
      price: 800.31,
      tmpProperty: undefined,
      activePromoId: 18,
    },
    {
      description: "deserunt minim et veniam",
      name: "dolor",
      price: 1410.39,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolor incididunt et officia",
      name: "Lorem",
      price: 359.29,
      tmpProperty: undefined,
      activePromoId: 69,
    },
    {
      description: "voluptate enim amet officia",
      name: "dolore",
      price: 1745.34,
      tmpProperty: undefined,
      activePromoId: 38,
    },
  ],
};
